import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { useLab } from "@/hooks/use-lab";
import { Architecture, Results, Pivot } from "@/components/ResearchGraphics";
import { TechnicalTrace } from "@/components/TechnicalTrace";
export const Route=createFileRoute("/recorded-run")({component:Lab});
function Lab(){const {state,events}=useLab();const s=state.data;const trail=events.data?.events??[];const [step,setStep]=useState(0);const [playing,setPlaying]=useState(false);useEffect(()=>{if(!playing)return;const timer=setInterval(()=>setStep(v=>{if(v>=trail.length-1){setPlaying(false);return v;}return v+1;}),2600);return()=>clearInterval(timer);},[playing,trail.length]);return <div className="demo-lab">
<p className="public-notice">Historical 24-request recorded run. <a href="/replication-g14/index.html">See the latest completed corrected replication →</a></p><section className="hero-grid"><div className="hero-copy"><div className="eyebrow">A RESEARCH LAB, WITH A MEMORY</div><h1>Science that<br/>learns its<br/><em>next move.</em></h1><p>An autonomous research lab that runs experiments, learns from results, and decides what to try next.</p><div className="hero-actions"><a href="#study" className="primary-action">Explore a real research loop <span>↗</span></a><span className="recorded-label"><i/> Recorded run · not live</span></div></div><Architecture/></section>
<div className="completion-strip"><span><i className="complete-mark">✓</i> Research loop completed</span><span>2 experimental batches · {s?.budget.used??"—"} model requests</span><strong>Model improvement not established</strong></div>
{state.error&&<p className="public-notice">The published research summary is unavailable. No live task is running from this page.</p>}
<section className="study-section" id="study"><div className="section-kicker">THE CASE / QWEN RELIABILITY</div><div className="study-heading"><h2>{s?.question??"Can Qwen use tools and numerical evidence more reliably without changing its weights?"}</h2><span className="study-tag">No weight updates</span></div><div className="decision-grid"><article><div className="eyebrow">DECISION AT THE END OF THE ORIGINAL RUN</div><h3>Reject the apparent win.</h3><p>{s?.decision??"The second batch scored higher, but its comparison was not fair. The candidate was not accepted."}</p></article><article><div className="eyebrow">ACCEPTED BEST AT THE END OF THE ORIGINAL RUN</div><h3>No accepted candidate</h3><p>{s?.best.summary??"A score alone is not enough. Scientific explanations and a valid comparison must also hold."}</p></article><article><div className="eyebrow">FOLLOW-UP COMPLETED</div><h3>Corrected retest completed.</h3><p>A separate 12-request equal-audit replication is complete. Neither arm met acceptance.</p></article></div></section>
<section className="research-section" id="results"><div className="section-title"><div><div className="section-kicker">MEASURE / THEN QUESTION</div><h2>Good scores need good evidence.</h2></div><Link to="/evidence">Research evidence ↗</Link></div>{s?.rounds?<Results rounds={s.rounds}/>:<p>Loading the published results…</p>}<p className="chart-footnote">Each batch used different fixtures. Compare arms within a batch; these are not a trend or a generalization claim.</p></section>
<section className="research-section" id="direction"><div className="section-title"><div><div className="section-kicker">RESULTS CHANGED THE PLAN</div><h2>A lab that can change its mind.</h2></div><span className="subtle-label">Historical decisions · corrected retest now complete</span></div><Pivot/><details className="research-details"><summary>Why the direction changed</summary><p>The first batch left answer labels and explanations inconsistent. The researcher then selected computed facts as a new approach. Independent review and the lead's protocol check found that the controller had not followed the instruction to provide identical facts to both arms. That implementation error invalidates the intended comparison; it is not solely a Qwen failure.</p></details></section>
<TechnicalTrace/>
<section className="replay-section" id="replay"><div className="section-title"><div><div className="section-kicker">RECORDED RUN · NOT LIVE</div><h2>Watch recorded run.</h2></div><button className="primary-action" disabled={!trail.length} onClick={()=>{if(step===trail.length-1)setStep(0);setPlaying(!playing);}}>{playing?"Pause recorded run":"Watch recorded run"}</button></div><div className="replay-progress">{trail.map((e,i)=><button key={e.id} className={i<=step?"seen":""} aria-label={`Show recorded event ${i+1}`} onClick={()=>{setStep(i);setPlaying(false);}}/>)}</div>{trail[step]&&<article className="replay-event"><span className="event-index">{String(step+1).padStart(2,"0")}</span><div><div className="eyebrow">{trail[step].role} · {trail[step].phase.replaceAll("_"," ")}</div><h3>{trail[step].summary}</h3><Link to="/evidence">Read the evidence summary ↗</Link></div></article>}<p className="small-note">Anonymized summaries of historical events, shown in sequence at a presentation pace—not their original timing. Playback never starts experiments or stops a worker.</p></section>
<section className="team-section"><div><div className="section-kicker">THE PEOPLE IN THE LOOP ARE AGENTS</div><h2>Codex researchers.<br/>Omnigent coordination.</h2><p>Omnigent via public <code>CodexExecutor</code>; persistent researcher and reviewer turns.</p><div className="handoff-strip"><b>Researcher A</b><span>turn 1 → review → turn 2</span><b>Reviewer B</b></div><p className="small-note">Bounded autonomy: these scientific turns read allowlisted evidence. They did not freely browse the web or edit experiment code. Codex model version: unknown.</p></div><div className="team-cards">{s?.agents.map(a=><article key={a.alias}><span className="eyebrow">{a.role}</span><b>{a.alias}</b><span>{a.turns?.length?`Recorded turns: ${a.turns.join(" · ")}`:"Research coordination"}</span></article>)}</div></section>
<section className="resource-section">{s?.resources.map(r=><article key={r.alias}><span className="resource-dot"/><div><b>{r.alias}</b><p>{r.task}</p><small>{r.status}</small></div></article>)}</section>
<section className="stop-test"><div><span className="eyebrow">STOP MECHANISM / CPU TEST</span><h3>Stopping is a saved decision.</h3><p>{s?.stop.summary??"Controlled CPU tasks verified saved stop intent, no new dispatch, confirmation and recovery. Real Qwen cancellation remains a future check."}</p></div><div className="stop-states"><span>Running</span><i>→</i><span>Stopping</span><i>→</i><span>Confirmed stopped</span></div></section>
<footer className="public-footer">An honest negative result is still useful research.<Link to="/evidence">Methods, limits & next step →</Link></footer></div>;}
