from pathlib import Path
import json,hashlib,datetime
ROOT=Path(__file__).resolve().parents[1]
G10=ROOT.parents[1]/'RS-20261004-G10/r1'
BASE=json.loads((G10/'config/experiment.json').read_text())['selected']['system']
C1=BASE+' For scientific evidence: unknown means no valid statistical test is supplied; reject means supplied p < pre-specified alpha; fail_to_reject means p >= alpha, and does not prove no effect or equivalence. Never replace unknown with not statistically significant. A numerical observed difference alone cannot establish causality. Use evidence exactly; do not infer an unreported test.'
C2=BASE+' Treat the supplied deterministic evidence audit as a factual tool result. Preserve its units and statistical test status in your answer. Explain uncertainty without adding unsupported causal claims.'
SCHEMA={'type':'object','properties':{'answer':{'type':'string'},'value':{'type':['number','null']},'explanation':{'type':'string'}},'required':['answer','value','explanation'],'additionalProperties':False}
def make_test(id,kind,input,expected,split):return {'id':id,'kind':kind,'input':input,'expected':expected,'split':'development-diagnostic','schema':None if kind=='tool' else SCHEMA}
TESTS=[make_test('N1','numeric',{'task':'Compare accuracy fractions, current minus reference in percentage points. answer=current/reference/tie, value=delta_pp. Explain evidence limits.','current':'0.7312','reference':'0.7305','evidence':'Single runs, different seeds; no statistical test.'},{'answer':'current','value':0.07},'development'),make_test('E1','evidence',{'task':'Classify statistical evidence as unknown/reject/fail_to_reject; value=null. Explain whether the treatment is established as beneficial.','observations':'Accuracy 0.721 vs 0.724 on two different seeds and machines. No statistical test or uncertainty interval supplied.'},{'answer':'unknown','value':None},'development'),make_test('E2','evidence',{'task':'Classify the supplied valid pre-specified two-sided test as unknown/reject/fail_to_reject; value=null. Explain what can and cannot be concluded.','facts':{'null':'zero mean paired accuracy difference','p':0.18,'alpha':0.05,'pre_specified':True,'valid_test':True,'equivalence_test':False}},{'answer':'fail_to_reject','value':None},'development'),make_test('N2','numeric',{'task':'Compare accuracy fractions, current minus reference in percentage points. answer=current/reference/tie, value=delta_pp. Explain evidence limits.','current':'0.8021','reference':'0.8096','evidence':'Single runs; no statistical test.'},{'answer':'reference','value':-0.75},'holdout'),make_test('E3','evidence',{'task':'Classify the supplied valid pre-specified two-sided test as unknown/reject/fail_to_reject; value=null. Explain whether association establishes causality.','facts':{'null':'zero mean paired accuracy difference','p':0.008,'alpha':0.01,'pre_specified':True,'valid_test':True,'design':'observational comparison, no randomized intervention'}},{'answer':'reject','value':None},'holdout'),make_test('T1','tool',{'task':'Call compare_decimal exactly once with left="0.8021", right="0.8096" as exact strings. Emit only the native call.'},{'tool':'compare_decimal','arguments':{'left':'0.8021','right':'0.8096'},'return':{'relation':'less','difference':'-0.0075'}},'holdout')]
def freeze(dest,choice):
 p=Path(dest);p.mkdir(parents=True,exist_ok=False)
 selected={'C1':C1,'C2':C2}[choice]
 tests=json.loads(json.dumps(TESTS))
 # C2 is a separately labeled system intervention, deterministic facts shared with both arms for a fair prompt comparison.
 if choice=='C2':
  for t in tests:
   if t['kind']!='tool':t['input']['deterministic_audit']=t['expected']
 conf={'run_id':'RS-20261004-G11-r1','batch_id':'batch-1','metric_version':'g11-v1','dataset_version':'fresh-fixture-v1','baseline':{'name':'G10 C1 reference prompt','system':BASE},'selected':{'name':choice,'system':selected},'tests':tests,'numeric_tolerance_pp':1e-9,'acceptance':'All objective fields correct within frozen tolerance; no material unsupported claims in reviewer original-text inspection. Both arms fail acceptance if any important explanation regression or unit error. Best comparison only within same metric+dataset.','limits':{'requests':12,'total_requests':24,'per_request_seconds':120,'total_experiment_seconds':1200},'sampling':{'temperature':0,'max_tokens':2048,'reasoning_effort':'none','parallel_tool_calls':False},'freeze_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'holdout':'Batch one is diagnostic. Any next-batch confirmation must use newly frozen unseen fixture outputs.'}
 (p/'config.json').write_text(json.dumps(conf,indent=2));(p/'FROZEN.sha256').write_text(hashlib.sha256((p/'config.json').read_bytes()).hexdigest())
 return conf
if __name__=='__main__':
 # Preparation only; no freezing until actual researcher selects.
 (ROOT/'control/candidate-spec.json').write_text(json.dumps({'candidates':[{'id':'C1','description':'Explicit unknown/reject/fail-to-reject evidence contract; pure prompt change.'},{'id':'C2','description':'Deterministic facts shared to both arms; evaluate explanation contract separately, cannot call model arithmetic improvement.'}],'tests':TESTS,'baseline':BASE,'candidate_prompts':{'C1':C1,'C2':C2},'note':'Proposed fixture; freeze only after Omnigent researcher chooses before inference.'},indent=2))
